### ISSUE TITLE
[roq-api] fatal error: range/v3/view.hpp: No such file or directory

### ISSUE THREAD

**Issue by shiyi23** [roq-trading/roq-issues#284]
**environment:**
Ubuntu18.04 
GCC10.4.0
cmake 3.24

**operation**
`make -j8`

**error message：**

> 
[ 85%] Building CXX object test/CMakeFiles/roq-api-test.dir/exceptions.cpp.o
[ 86%] Building CXX object test/CMakeFiles/roq-api-test.dir/json.cpp.o
In file included from /opt/roq-api/test/json.cpp:5:
/opt/roq-api/include/roq/json/market_by_price_update.hpp:7:10: fatal error: range/v3/view.hpp: No such file or directory
    7 | #include <range/v3/view.hpp>
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
test/CMakeFiles/roq-api-test.dir/build.make:187: recipe for target 'test/CMakeFiles/roq-api-test.dir/json.cpp.o' failed
make[2]: *** [test/CMakeFiles/roq-api-test.dir/json.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:978: recipe for target 'test/CMakeFiles/roq-api-test.dir/all' failed
make[1]: *** [test/CMakeFiles/roq-api-test.dir/all] Error 2
Makefile:145: recipe for target 'all' failed
make: *** [all] Error 2

@thraneh could you help me？

**Comment by thraneh** [comment]
Hi,

First, you don't benefit much from trying to build the API. Everything behind the API is closed source (gateways and the client library).

Second, the code is only meant to be used with the miniforge/conda package manager which comes with its own build environment (it provides complete isolation from the host environment).

You could follow the instructions from the roq-samples README, then you should get a proper environment to also build the API.

https://github.com/roq-trading/roq-samples

**Comment by thraneh** [comment]
The README from roq-api has now been updated to reflect the missing dependency that you found

![image](https://user-images.githubusercontent.com/3802151/193745977-8fa6315d-4e10-433d-82e4-93a1dfac0439.png)

**Comment by shiyi23** [comment]
> The README from roq-api has now been updated to reflect the missing dependency that you found
> 
> ![image](https://user-images.githubusercontent.com/3802151/193745977-8fa6315d-4e10-433d-82e4-93a1dfac0439.png)

Thank you very much, sir!

**Comment by shiyi23** [comment]
@thraneh  My I ask a question: Is there any plan to open source the code of gateways and the client?

**Comment by thraneh** [comment]
No.

As much as possible is being open sourced: API (the interface) + more and more of the tooling. There is also lots of online documentation freely available as well. The intention is to give you almost full insight into how it all works.

The guiding principle is to avoid lock-ins in the sense that you can start using the gateways and build your own trading infrastructure. You have access to everything (with a MIT license for the API) so that you later can decide to implement your own gateways behind the interface.

However, the license costs are quite agreeable if you're a professional using the software. You will find that it's a fraction of the price charged by other vendors (who will also typically only give you access to 100% closed source with very restrictive contractual terms).

**Comment by shiyi23** [comment]
> No.
> 
> As much as possible is being open sourced: API (the interface) + more and more of the tooling. There is also lots of online documentation freely available as well. The intention is to give you almost full insight into how it all works.
> 
> The guiding principle is to avoid lock-ins in the sense that you can start using the gateways and build your own trading infrastructure. You have access to everything (with a MIT license for the API) so that you later can decide to implement your own gateways behind the interface.
> 
> However, the license costs are quite agreeable if you're a professional using the software. You will find that it's a fraction of the price charged by other vendors (who will also typically only give you access to 100% closed source with very restrictive contractual terms).

Thank you sir, thank you very much for your detailed answer!
