### ISSUE TITLE
roq-deribit install dependency error

### ISSUE THREAD

**Issue by sculd** [roq-trading/roq-issues#305]
Hi,

As described [here](https://roq-trading.com/docs/tutorials/conda/),

after

> % conda install abseil-cpp

doing this

> % conda install -y --channel https://roq-trading.com/conda/stable roq-deribit
> Collecting package metadata (current_repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
> Collecting package metadata (repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Solving environment: -
> Found conflicts! Looking for incompatible packages.
> This can take several minutes. Press CTRL-C to abort.
> failed
> 
> UnsatisfiableError: The following specifications were found to be incompatible with each other:
> 
> Output in format: Requested package -> Available versions
> 
> Package libcxx conflicts for:
> abseil-cpp -> libcxx[version='>=12.0.0']
> roq-deribit -> libcxx[version='>=14.0.6']
> libcxx

causes dependency issue. I would like to report this issue here.

Thank you.

**Comment by thraneh** [comment]
Hi,

I will look at this in the morning (European time).

However, could it be that you’re using another package repository than
conda-forge?

For example, anaconda (miniconda) is very slow at updating the compilers.

**Comment by thraneh** [comment]
I tried to create a clean conda environment using Miniforge.

I then tried to install roq-deribit with and without installing abseil-cpp first (recreated environment in between).

In both cases it succeeded.

Then I tried to install Miniconda followed by installing roq-deribit.

It indeed failed with package conflicts. Slightly different from what you wrote:

```
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                                                                                                                                                                                                      

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package libgcc-ng conflicts for:
python=3.9 -> zlib[version='>=1.2.11,<1.3.0a0'] -> libgcc-ng[version='>=7.2.0']
python=3.9 -> libgcc-ng[version='>=11.2.0|>=7.5.0|>=7.3.0']

Package libstdcxx-ng conflicts for:
python=3.9 -> libstdcxx-ng[version='>=11.2.0|>=7.5.0|>=7.3.0']
roq-deribit -> libstdcxx-ng[version='>=12']The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.35=0
  - feature:|@/linux-64::__glibc==2.35=0

Your installed version is: 2.35

```

I didn't try with Anaconda, but it should just be a heavier version of Miniconda.

**Comment by thraneh** [comment]
In summary, I think you might be using a different package repository than conda-forge OR you have installed something in your environment that does not support the latest GCC compiler (or glibc).

**Comment by thraneh** [comment]
There is another possible reason: it looks like conda-forge had new packages pushed for abseil-cpp just yesterday.

* https://anaconda.org/conda-forge/abseil-cpp/files

We have previously seen issues with the package manager choosing the wrong version of some package. The reason hasn't always been obvious, but it could be related to the "head" package being removed while a new version is build built/published.

If you were indeed using Miniforge, could you try again, please?

**Comment by thraneh** [comment]
Closing this issue due to missing feedback from reporter.
