### ISSUE TITLE
[roq-api] Q: Multithreading and custom types of events support

### ISSUE THREAD

**Issue by jkawnkwh85** [roq-trading/roq-issues#312]
1. It seems that a strategy is supposed to run in a single thread. Does roq support running the same strategies in different threads so that the trading can be automatically distributed to different threads?
2. We are interested in support of custom types of events. For example, we would like to reconstruct the order book from trade and order events, take higher frequency snapshots from the rebuilt order book and make a strategy react on these new events. Is roq possible to support this use case?
3. Another use case for customized types of events is that we often predict the short-term volatility of securities. However, we would like to separate the implementation of volatility prediction from the implementation of strategies so that all strategies do not need to repeat the work. Ideally, the calculation is implemented as another micro-service, it publishes `Event<Volatility>` to roq so that all strategies can subscribe.

**Comment by thraneh** [comment]
All of it is possible.

I will paste some links so you can investigate further.

Please refer to the interfaces for a strategy:

* The [Handler](https://github.com/roq-trading/roq-api/blob/master/include/roq/client/handler.hpp) supports incoming events.
* The [Dispatcher](https://github.com/roq-trading/roq-api/blob/master/include/roq/client/dispatcher.hpp) supports outgoing events.

1. Threading

You can use the `Start` And `Stop` events to manage other threads. It is demonstrated in [example-5](https://github.com/roq-trading/roq-samples/tree/master/src/roq/samples/example-5)

However, you must ensure that all outgoing events are sent from the primary thread that the strategy runs from. None of the interfaces are thread-safe (for performance reasons).

2. Timer based events

You can use a [`cache::MarketByPrice`](https://github.com/roq-trading/roq-api/blob/master/include/roq/cache/market_by_price.hpp) object to maintain the L2 order book based on an initial snapshot (received when you connect to the gateway) and the following incremental updates.

You can use the `Timer` event from the `Handler` to extract the order book snapshot.

At this point you can do your computations, forward to other threads, or whatever you like.

> Do you really mean "higher" frequency snapshots? Probably "lower" frequency than real-time...?

3. Distributed calculations

Just launch another strategy with the only purpose being the computation of a custom metrics.

Publish a [`CustomMetrics`](https://github.com/roq-trading/roq-api/blob/master/include/roq/custom_metrics.hpp) via the `Dispatcher` interface.

> These updates are key-value pairs (string and double). Each such set of key-value pairs can be identified by account/exchange/symbol (all optional) and a label.

Other strategies can then receive these custom values. This is demonstrated in [example-7](https://github.com/roq-trading/roq-samples/tree/90e5109c2a79ce9b9a409e69d4de70b6e6c7bf38/src/roq/samples/example-7).
