### ISSUE TITLE
[roq-api] Errors on make, mac os basic_format_parse_context<char> is unavailable

### ISSUE THREAD

**Issue by burgerpig** [roq-trading/roq-issues#436]
Hi, I tried to make the roq-api, but just encounter some error while making.

The errors looks like this. I was following the instructions on the README.md.

my macOS is 12.6.4.
clang version: clang version 17.0.6
Target: x86_64-apple-darwin21.6.0

Thanks for your help!

~/conda/bin/../include/c++/v1/__format/format_parse_context.h:91:30: error: 'basic_format_parse_context<char>' is unavailable
   91 | using format_parse_context = basic_format_parse_context<char>;
      |                              ^
~/conda/bin/../include/c++/v1/__format/format_parse_context.h:26:56: note: 'basic_format_parse_context<char>' has been explicitly marked unavailable here
   26 | class _LIBCPP_TEMPLATE_VIS _LIBCPP_AVAILABILITY_FORMAT basic_format_parse_context {
      |                                                        ^

**Comment by thraneh** [comment]
Hi,

Thanks for reporting.

This is a known issue. Currently it’s only possible to build with clang 16

Best
Hans

**Comment by thraneh** [comment]
You need `-D_LIBCPP_DISABLE_AVAILABILITY` as described here: https://conda-forge.org/docs/maintainer/knowledge_base.html#newer-c-features-with-old-sdk
